FROM node:7.2

LABEL maintainer="Lincoln Brito <lincoln.sbrito@gmail.com>"
LABEL description="Vue CLI image"

RUN apt-get install -y git \
    && npm install --quiet --global yarn@1.3.2 gulp@3.9.1 webpack@3.10.0 vue-cli@2.9.2 \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html

EXPOSE 8080
EXPOSE 3000

CMD ["yarn", "run", "start"]