FROM node:7.2

LABEL maintainer="Lincoln Brito <lincoln.sbrito@gmail.com>"
LABEL description="Angular CLI image"

RUN apt-get install -y git \
    && npm install --quiet --global yarn@1.3.2 @angular/cli \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html

EXPOSE 4200
EXPOSE 49153

CMD ["yarn", "run", "start"]