#!/bin/bash

USER="lincolnbrito"
TIMESTAMP=$(date "+%Y%m%d%H%M")

api() {
    echo "Construindo a imagem ${USER}/api:${TIMESTAMP}"
    docker build -f api/Dockerfile -t ${USER}/api:${TIMESTAMP} ./api

    echo "Marcando a tag latest também"
    docker tag ${USER}/api:${TIMESTAMP} ${USER}/api:latest

    #echo "Enviando a imagem para nuvem docker"
    #docker push ${USER}/api:${TIMESTAMP}
    #docker push ${USER}/api:latest
}

angular() {
    echo "Construindo a imagem ${USER}/node-angular-cli:${TIMESTAMP}"
    docker build -f node-angular-cli/Dockerfile -t ${USER}/node-angular-cli:${TIMESTAMP} .

    echo "Marcando a tag latest também"
    docker tag ${USER}/node-angular-cli:${TIMESTAMP} ${USER}/node-angular-cli:latest

    #echo "Enviando a imagem para nuvem docker"
    #docker push ${USER}/node-angular-cli:${TIMESTAMP}
    #docker push ${USER}/node-angular-cli:latest
}

vue() {
    echo "Construindo a imagem ${USER}/node-vue-cli:${TIMESTAMP}"
    docker build -f node-vue-cli/Dockerfile -t ${USER}/node-vue-cli:${TIMESTAMP} .

    echo "Marcando a tag latest também"
    docker tag ${USER}/node-vue-cli:${TIMESTAMP} ${USER}/node-vue-cli:latest

    #echo "Enviando a imagem para nuvem docker"
    #docker push ${USER}/node-vue-cli:${TIMESTAMP}
    #docker push ${USER}/node-vue-cli:latest
}

all() {
    build_api
    build_angular
    build_vue
}

if [ $# -gt 0 ]; then
    "$@"
else
    echo "#### Script de build de imagens docker ####"
    echo "Opções:"
    echo "- build all:      constrói todas as imagens"
    echo "- build angular:  constrói a imagem node-angular-cli"
    echo "- build vue:      constrói a imagem node-vue-cli"
    echo "- build api:      constrói a imagem api (laravel)"
fi

#docker build -f webapp/Dockerfile-vue -t lincolnbrito/webapp-vue:latest ./webapp
#docker build -f webapp/Dockerfile-angular -t lincolnbrito/webapp-angular:latest ./webapp
#docker build -f api/Dockerfile -t lincolnbrito/api:latest ./api